(define memories
  '((memory flash (address (#xf80000 . #xffffff))
  		(fill 0)
	    (section
			(LoCodeStorage #xffe000)
		    (VectorStorage #xffffe0)))
    (memory DirectPage (address (#x00c000 . #x00c0ff))
        (section (registers ztiny)))
    (memory LoRAM (address (#x00c100 . #x00efff))
        (section stack data zdata data heap))
    (memory NearRAM1 (address (#x050000 . #x057fff))
        (section znear near))
    (memory NearRAM2 (address (#x058000 . #x05ffff))
        (section cnear))
    (memory FarRAM1 (address (#x060000 . #x06ffff))
        (section far huge))
    (memory FarRAM2 (address (#x070000 . #x07ffff))
        (section zfar zhuge))
    (memory LoCode (address (#x00e000 . #x00ffdf))
		(scatter-to LoCodeStorage)
        (section code cdata (jumptable #x00e000)))
    (memory Vector (address (#x00ffe0 . #x00ffff))
		(scatter-to VectorStorage)
        (section (reset #xfffc)))
    (memory HiCode1 (address (#xf80000 . #xf8ffff))
	    (section cfar switch data_init_table ifar farcode))
    (memory HiCode2 (address (#xf90000 . #xf9ffff))
	    (section cfar switch data_init_table ifar farcode))
    (memory HiCode3 (address (#xfa0000 . #xfaffff))
	    (section cfar switch data_init_table ifar farcode))
    (block stack (size #x1000))
    (block heap (size #x1000))
    (base-address _DirectPageStart DirectPage 0)
    (base-address _NearBaseAddress NearRAM1   0)
))
